// Responsive hero image variants generated by vite-imagetools
// 1120w desktop, 768w tablet, 480w mobile; webp preferred with png fallback
import earth480wWebp from '../../assets/Images/EarthImage.png?format=webp&width=480';
import earth768wWebp from '../../assets/Images/EarthImage.png?format=webp&width=768';
import earth1120wWebp from '../../assets/Images/EarthImage.png?format=webp&width=1120';
import earth480wPng from '../../assets/Images/EarthImage.png?width=480';
import earth768wPng from '../../assets/Images/EarthImage.png?width=768';
import earth1120wPng from '../../assets/Images/EarthImage.png?width=1120';
import {Link} from 'react-router'
import Featurecardgrid from './Featurecard'
const HeroSection = () => {
  return (<>
    <section className="bg-black text-white h-4/7 flex flex-col ">
      <div className="max-w-[1400px] mx-auto w-full px-6">
        
        {/* Left Content */}
        <div className="pt-60 flex flex-col justify-center">
          <h1 className="text-center md:text-left text-3xl md:text-4xl lg:text-5xl font-extrabold leading-snug font-Merriweather">
            MOST RESPONSIVE & <br /> INNOVATIVE IT <br /> SOLUTIONS FOR <br /> BUSINESSES
          </h1>
          <Link to='/get-in-touch' className='text-center md:text-left pt-5'>
          <button className="bg-gradient-to-r from-[#49eec3] to-[#2bb892] text-black font-semibold px-6 py-3 rounded-lg shadow-md w-fit hover:opacity-90 transition cursor-pointer">
            Contact us
          </button>
          </Link>
        </div>

        {/* Right Content (Earth Image) */}
        <div className=" hidden md:block z-0">
          <picture>
            <source
              type="image/webp"
              srcSet={`${earth480wWebp} 480w, ${earth768wWebp} 768w, ${earth1120wWebp} 1120w`}
              sizes="(max-width: 640px) 480px, (max-width: 1024px) 768px, 1120px"
            />
            <img
              src={earth1120wPng}
              srcSet={`${earth480wPng} 480w, ${earth768wPng} 768w, ${earth1120wPng} 1120w`}
              sizes="(max-width: 640px) 480px, (max-width: 1024px) 768px, 1120px"
              alt="Earth"
              className=" absolute left-185 -top-17 w-4xl  "
              loading="eager"
              decoding="async"
              fetchpriority="high"
            />
          </picture>
        </div>
        
      </div>
     <div className="mt-25 px-6 pb-20 pt-10 md:px-12 ">
          <Featurecardgrid />
        </div>
    </section>
    
     </>
  )
}

export default HeroSection